# Generated by Django 4.2.2 on 2023-06-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_classes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=5),
        ),
    ]
